# Problem Specification YAML File Keys
VARIABLES = 'variables'
INPUT = 'input'
OUTPUT = 'output'
NAME = 'name'
MIN = 'min'
MAX = 'max'
STEP = 'step'
VALUE = 'value'
LEVELS = 'levels'
MF_TYPE = 'mf_type'
MF_PARAMS = 'mf_params'
TRIANGLE = 'triangle'
RULES = 'rules'
WEIGHT = 'weight'
ANTECEDENT = 'antecedent'
OPERATOR = 'operator'
LEVEL = 'level'
AND = 'and'
OR = 'or'
SUM = 'sum'
CONSEQUENT = 'consequent'
IMPLICATION = 'implication'
AGGREGATION = 'aggregation'
DEFUZZIFICATION = 'defuzzification'
CENTROID = 'centroid'

X = 'x'
VALUES = 'values'
MF = 'mf'
MFS = 'mfs'
IMPMF = 'impmf'
FUZZY_VALUES = 'fuzzy_values'
AGGRMF = 'aggrmf'
AVERAGE = 'average'

# Defaults
DEFAULTS_FILE = 'defaults.yaml'
DEFAULT_MF_TYPE = TRIANGLE
INTERVALS = 10
